(defconst demo-packages
  '(
    ace-isearch
    ace-jump-helm-line
    ace-jump-mode
    anzu
    async
    autopair
    avy
    bookmark+
    buffer-move
    clean-aindent-mode
    clean-buffers
    cmake-mode
    company
    company-c-headers
    company-irony
    company-irony-c-headers
    company-statistics
    company-try-hard
    company-flx
    comment-dwim-2
    cmake-project
    dash
    diffview
    digit-groups
    dired+
    dired-filter
    dired-sort
    dired-dups
    dired-subtree
    helm-flyspell
    flyspell-correct-helm
    flyspell-lazy
    dtrt-indent
    dummyparens
    duplicate-thing
    embrace
    epl
    expand-line
    expand-region
    flycheck
    flycheck-irony
    frame-cmds
    frame-fns
    function-args
    fuzzy
    ggtags
    git-commit
    gitignore-mode
    google-this
    helm
    helm-company
    helm-core
    helm-flx
    helm-flycheck
    helm-fuzzier
    helm-git
    helm-gitignore
    helm-gtags
    helm-projectile
    helm-swoop
    iedit
    image+
    image-file
    image-dired+
    irony
    ivy
    isearch+
    iy-go-to-char
    let-alist
    magit
    magit-filenotify
    magit-gitflow
    magit-popup
    pkg-info
    popup
    projectile
    request
    seq
    smartparens
    smartscan
    swiper
    undo-tree
    volatile-highlights
    which-key
    with-editor
    ws-butler
    xterm-color
    yafolding
    yasnippet
    zygospore



    (defconst packages-to-remove
      '(
        icicles
        xcscope
        helm-cscope
        ace-flyspell

        )
      )))
